# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Wait for commit statuses
      id: waitforstatuschecks
      uses: WyriHaximus/github-action-wait-for-status@0.1.0
      with:
        ignoreActions: Comment
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Get branch name
      uses: nelonoel/branch-name@v1

    - name: Comment Pull Request
      uses: thollander/actions-comment-pull-request@1.0.0
      with:
        # Message that should be printed in the pull request
        message: "Example!!!"
        # Github token of the repository (automatically created by Github)
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
